import { Loader2, Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { useStoryContext } from "@/features/stories/context/StoryContext";
import {
    useAddFavoriteMutation,
    useFavoritesQuery,
    useGenerateNamesMutation,
    useMarkNameUsedMutation,
    useRemoveFavoriteMutation,
    useUsedNamesQuery
} from "@/features/name-generator/hooks/useNameGeneratorQuery";
import { GeneratedNameRow } from "@/features/name-generator/components/GeneratedNameRow";
import type { GenerateNamesResponse, UsedNameType } from "@/types/nameGenerator";
import type { ParsedNameProposal } from "../services/parseNameProposal";

interface NameProposalCardProps {
    proposal: ParsedNameProposal;
    storyId: string;
}

const kindToNameType = (kind: ParsedNameProposal["kind"]): UsedNameType => (kind === "first_name" ? "first" : "surname");

// NG6 — sibling to PsychProposalCard/ProseProposalCard, but there's no single value to Accept/
// Reject: the model is requesting the (non-LLM, deterministic) generate action run, so this card
// runs it once on mount and renders results with the same per-name Copy/Use/Create-Codex actions
// GeneratedNameRow gives the panel (NG2) — reused directly rather than duplicated. Never writes
// anything on its own; only "Use" (marks used) or "Create Codex" (opens the review dialog) do,
// exactly like the panel.
export function NameProposalCard({ proposal, storyId }: NameProposalCardProps) {
    const { setPendingLorebookSeed, setCurrentTool } = useStoryContext();
    const [result, setResult] = useState<GenerateNamesResponse | null>(null);
    const hasGenerated = useRef(false);

    const generateMutation = useGenerateNamesMutation();
    const markUsedMutation = useMarkNameUsedMutation();
    const { data: usedData } = useUsedNamesQuery(storyId);
    const { data: favoritesData } = useFavoritesQuery(storyId);
    const addFavoriteMutation = useAddFavoriteMutation();
    const removeFavoriteMutation = useRemoveFavoriteMutation();

    useEffect(() => {
        if (hasGenerated.current) return;
        hasGenerated.current = true;
        generateMutation.mutate(
            {
                storyId,
                kind: proposal.kind,
                gender: proposal.gender,
                region: proposal.region,
                era: proposal.era,
                count: proposal.count
            },
            { onSuccess: setResult }
        );
        // Fires once per card instance — proposal/storyId are stable for the message this card
        // renders for, and generateMutation is a fresh object every render (react-query).
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const nameType = kindToNameType(proposal.kind);
    const usedNameSet = new Set((usedData?.usedNames ?? []).filter(u => u.nameType === nameType).map(u => u.name.toLowerCase()));
    const favoritedNames = new Set(
        (favoritesData?.favorites ?? []).filter(f => f.nameType === nameType).map(f => f.name.toLowerCase())
    );

    const handleCreateCodexEntry = (name: string) => {
        setPendingLorebookSeed({ name, category: "character", blurb: "Needs fleshing out — generated by the Name Generator." });
        setCurrentTool("lorebook");
    };

    const handleToggleFavorite = (name: string, poolId: string) => {
        const existing = favoritesData?.favorites.find(f => f.nameType === nameType && f.name.toLowerCase() === name.toLowerCase());
        if (existing) removeFavoriteMutation.mutate({ storyId, id: existing.id });
        else addFavoriteMutation.mutate({ storyId, name, nameType, poolId });
    };

    return (
        <Card className="border-dashed">
            <CardHeader className="pb-2">
                <div className="flex items-center gap-2">
                    <Badge variant="outline">
                        <Sparkles className="h-3 w-3 mr-1" />
                        Name Generator
                    </Badge>
                    <span className="text-sm text-muted-foreground">
                        {proposal.kind === "first_name" ? "First name" : "Surname"} suggestions
                        {proposal.region ? ` — ${proposal.region}` : ""}
                    </span>
                </div>
            </CardHeader>
            <CardContent className="space-y-2">
                {generateMutation.isPending && (
                    <div className="flex items-center gap-2 text-sm text-muted-foreground py-2">
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Generating...
                    </div>
                )}
                {result?.names.length === 0 && (
                    <p className="text-sm text-muted-foreground">No names matched those filters.</p>
                )}
                {result?.names.map((name, index) => (
                    <GeneratedNameRow
                        key={`${name.poolId}-${name.name}-${index}`}
                        result={name}
                        nameType={nameType}
                        isUsed={usedNameSet.has(name.name.toLowerCase())}
                        markUsedPending={markUsedMutation.isPending}
                        onMarkUsed={() =>
                            markUsedMutation.mutate({ storyId, name: name.name, nameType, source: "generated", poolNameId: undefined })
                        }
                        onCreateCodexEntry={() => handleCreateCodexEntry(name.name)}
                        isFavorited={favoritedNames.has(name.name.toLowerCase())}
                        favoritePending={addFavoriteMutation.isPending || removeFavoriteMutation.isPending}
                        onToggleFavorite={() => handleToggleFavorite(name.name, name.poolId)}
                    />
                ))}
            </CardContent>
        </Card>
    );
}
