import type { PromptMessage } from "../../src/types/story.js";

// Unofficial, reverse-engineered client for grok.com's internal (undocumented) chat API, used
// to drive a SuperGrok subscription via a pasted browser session cookie since xAI does not
// offer a public API for the consumer product. The URL, request body, and response shape below
// are all calibrated against a real captured request/response pair (DevTools Network tab).
//
// Known open risk: grok.com sends a per-request `x-statsig-id` header generated by its
// client-side JS (an anti-bot signature, differs per request) that we cannot replicate — it's
// intentionally omitted below. If grok.com's backend hard-requires it, requests will fail
// regardless of everything else being correct; there's no way to know without testing live.
const GROK_CONVERSATION_URL = "https://grok.com/rest/app-chat/conversations/new";

const roleLabel = (role: PromptMessage["role"]): string => {
    if (role === "system") return "System";
    if (role === "assistant") return "Assistant";
    return "User";
};

// grok.com's conversation API is stateful (each conversation has server-side history), but our
// callers always send the full message array stateless-style on every call (same as every other
// provider here) — so we flatten it into one prompt and always start a fresh conversation.
const flattenMessages = (messages: PromptMessage[]): string =>
    messages.map(m => `${roleLabel(m.role)}: ${m.content}`).join("\n\n");

// grok.com streams a sequence of top-level JSON objects with no reliable delimiter between them
// (DevTools shows them pretty-printed; the raw wire format may or may not be one-per-line), so
// this scans char-by-char tracking brace depth (respecting string literals) to pull out each
// complete object as it completes, carrying any trailing partial object over to the next call.
const extractJsonObjects = (buffer: string): { objects: unknown[]; rest: string } => {
    const objects: unknown[] = [];
    let i = 0;
    let start = -1;
    let depth = 0;
    let inString = false;
    let escape = false;

    while (i < buffer.length) {
        const ch = buffer[i];
        if (start === -1) {
            if (ch === "{") {
                start = i;
                depth = 1;
            }
            i++;
            continue;
        }

        if (inString) {
            if (escape) escape = false;
            else if (ch === "\\") escape = true;
            else if (ch === '"') inString = false;
        } else if (ch === '"') inString = true;
        else if (ch === "{") depth++;
        else if (ch === "}") {
            depth--;
            if (depth === 0) {
                try {
                    objects.push(JSON.parse(buffer.slice(start, i + 1)));
                } catch {
                    // malformed/truncated object — skip it rather than fail the whole stream
                }
                start = -1;
            }
        }
        i++;
    }

    return { objects, rest: start === -1 ? "" : buffer.slice(start) };
};

// Each streamed object may carry a "thinking" token (grok's internal reasoning, shown collapsed
// in the UI, e.g. "Thinking about your request") ahead of the actual reply tokens — those are
// tagged isThinking: true and must be skipped so they don't leak into the generated text.
const extractToken = (obj: unknown): string | undefined => {
    const response = (obj as { result?: { response?: { token?: string; isThinking?: boolean } } })?.result
        ?.response;
    if (!response || response.isThinking) return undefined;

    const token = response.token;
    return typeof token === "string" && token.length > 0 ? token : undefined;
};

export async function* streamGrokSession(
    cookie: string,
    messages: PromptMessage[],
    model: string,
    signal?: AbortSignal
): AsyncGenerator<string> {
    const response = await fetch(GROK_CONVERSATION_URL, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Accept: "*/*",
            Origin: "https://grok.com",
            Referer: "https://grok.com/",
            "User-Agent":
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36 Edg/150.0.0.0",
            "sec-ch-ua": '"Not;A=Brand";v="8", "Chromium";v="150", "Microsoft Edge";v="150"',
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": '"Windows"',
            "sec-fetch-dest": "empty",
            "sec-fetch-mode": "cors",
            "sec-fetch-site": "same-origin",
            "x-xai-request-id": crypto.randomUUID(),
            Cookie: cookie
        },
        body: JSON.stringify({
            temporary: false,
            message: flattenMessages(messages),
            fileAttachments: [],
            imageAttachments: [],
            disableSearch: false,
            enableImageGeneration: true,
            returnImageBytes: false,
            returnRawGrokInXaiRequest: false,
            enableImageStreaming: true,
            imageGenerationCount: 2,
            forceConcise: false,
            enableSideBySide: true,
            sendFinalMetadata: true,
            disableTextFollowUps: false,
            responseMetadata: {},
            disableMemory: false,
            forceSideBySide: false,
            isAsyncChat: false,
            disableSelfHarmShortCircuit: false,
            collectionIds: [],
            disabledConnectorIds: [],
            deviceEnvInfo: {
                darkModeEnabled: true,
                devicePixelRatio: 1,
                screenWidth: 1920,
                screenHeight: 1080,
                viewportWidth: 1357,
                viewportHeight: 914
            },
            modeId: model
        }),
        signal
    });

    if (!response.ok || !response.body) {
        const body = await response.text().catch(() => "");
        throw new Error(`grok.com request failed: ${response.status} ${response.statusText} ${body}`.trim());
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    try {
        while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            buffer += decoder.decode(value, { stream: true });
            const { objects, rest } = extractJsonObjects(buffer);
            buffer = rest;

            for (const obj of objects) {
                const token = extractToken(obj);
                if (token) yield token;
            }
        }
    } finally {
        reader.releaseLock();
    }
}
